filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - ./log/application.log
output.kafka:
  codec.format:
    string: '%{[@timestamp]} %{[message]}'
  hosts: ["kafka1:9092"]
  topic: workplaces
  partition.round_robin:
    reachable_only: false
  required_acks: 1
  compression: gzip
  max_message_bytes: 1000000